<?php

declare(strict_types=1);

use Ynamite\Media\Config;

if (!Config::signKey()) {
    Config::set(Config::KEY_SIGN_KEY, bin2hex(random_bytes(32)));
}

$cacheDir = rex_path::addonAssets(Config::ADDON, 'cache/');
if (!is_dir($cacheDir)) {
    rex_dir::create($cacheDir);
}

// Recursively normalise cache/ permissions to 0755 dirs / 0644 files. Why
// this is in install (not just at runtime via Glide's filesystem visibility):
// existing variant directories created BEFORE the visibility fix have mode
// 0700 (Flysystem's PortableVisibilityConverter default, see
// `Glide\Server::publicVisibility`). On shared hosting where PHP-FPM and
// Apache run as different users (typical Plesk / cPanel setup), Apache
// cannot traverse those directories — every cache-hit URL returns 403 with
// `pcfg_openfile: ensure ... is executable` in the server log. Newly
// created variant directories pick up 0755 from the visibility fix; this
// migration resurrects the broken-perm legacy ones. `@chmod` is silenced
// so a single permission-denied entry in a sub-tree doesn't abort the whole
// reinstall — Apache still 403s on the unfixable subtree, but the rest of
// the cache works.
if (is_dir($cacheDir)) {
    @chmod($cacheDir, 0755);
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($cacheDir, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST,
    );
    foreach ($iterator as $entry) {
        @chmod($entry->getPathname(), $entry->isDir() ? 0755 : 0644);
    }
}

// REDAXO's installAssets() copies via rex_finder which has ignoreSystemStuff
// on by default — that filter drops anything starting with `.git` (intended
// for `.git/` directories, but also catches `.gitignore`). The shipped
// `assets/.gitignore` therefore never reaches the runtime location, so we
// write it from here. Lives one level above cache/ so neither the
// CACHE_DELETED hook nor the manual "Cache leeren" button (both of which
// recurse into cache/) can wipe it.
$gitignorePath = rex_path::addonAssets(Config::ADDON, '.gitignore');
if (!is_file($gitignorePath)) {
    rex_file::put($gitignorePath, "cache/\n");
}

// `_img/index.php` (runtime cache-miss handler) needs the same `$REX` setup
// the htdocs frontend `index.php` provides — REDAXO core's `boot.php` requires
// `HTDOCS_PATH`, `BACKEND_FOLDER`, `REDAXO` (and `PATH_PROVIDER` on installs
// with a non-default path provider) plus `LOAD_PAGE = true` to actually
// register and boot addons. Without `LOAD_PAGE`, `core/boot.php` finishes
// framework setup and returns; the `frontend.php` → `packages.php` chain that
// populates `rex_addon::$addons[]` and dispatches `PACKAGES_INCLUDED` never
// runs, so `rex_addon::get('massif_media')` returns the null-stub and any
// method call on it fatals. None of `rex_path::*` is available pre-boot, so
// resolve everything here via the live path provider and write a self-
// contained bootstrap script to `_img/.bootstrap.php`. Path-provider-aware:
// standard `<htdocs>/redaxo/...` and offset layouts (Viterex `app_path_provider`,
// custom providers) both work. Note ordering: REDAXO copies `assets/` *after*
// install.php runs (`rex_package_manager::install()` line 143 vs 177), but
// `rex_dir::copy` is non-destructive — iterates source files only — so the
// hand-written bootstrap survives the asset copy. Re-runs on every
// install/reinstall, so BACKEND_FOLDER renames or site-moves are picked up
// automatically.
$bootstrapPath = rex_path::addonAssets(Config::ADDON, '_img/.bootstrap.php');
$pathProvider = rex::getProperty('path_provider');
$htdocsPath = rex_path::frontend();
$bootPath = rex_path::core('boot.php');
$backendFolder = trim(substr(rex_path::backend(), strlen($htdocsPath)), '/');
if ('' === $backendFolder) {
    $backendFolder = 'redaxo';
}

$bootstrapLines = [
    '<?php',
    '',
    '// Generated by massif_media install.php — do not edit, regenerated on every install.',
    '// Provides the $REX setup REDAXO core boot.php requires when bootstrapped from',
    '// outside the standard frontend/backend entry points (cache-miss path through',
    '// <htdocs>/assets/addons/massif_media/_img/index.php). LOAD_PAGE=true is what',
    '// makes core/boot.php proceed to frontend.php → packages.php; without it the',
    '// addon never registers and rex_addon::get() returns the null-stub.',
    '',
    '$REX = [];',
    '$REX[\'REDAXO\'] = false;',
    '$REX[\'HTDOCS_PATH\'] = ' . var_export($htdocsPath, true) . ';',
    '$REX[\'BACKEND_FOLDER\'] = ' . var_export($backendFolder, true) . ';',
    '$REX[\'LOAD_PAGE\'] = true;',
];

// Custom path provider (e.g. Viterex's `app_path_provider`, which puts htdocs
// at `<project>/public/` and REDAXO core at `<project>/src/core/`). Inject
// the same way the htdocs index.php does — capture the file path and class
// name now, instantiate at runtime. Assumes a no-arg constructor (the only
// pattern in the wild we know of); a non-default ctor signature would need
// hand-editing.
if ($pathProvider instanceof rex_path_default_provider && get_class($pathProvider) !== 'rex_path_default_provider') {
    $reflection = new ReflectionClass($pathProvider);
    $providerFile = $reflection->getFileName();
    if ($providerFile && is_file($providerFile)) {
        $bootstrapLines[] = '';
        $bootstrapLines[] = 'require ' . var_export($providerFile, true) . ';';
        $bootstrapLines[] = '$REX[\'PATH_PROVIDER\'] = new \\' . get_class($pathProvider) . '();';
    }
}

$bootstrapLines[] = '';
$bootstrapLines[] = 'require ' . var_export($bootPath, true) . ';';

rex_file::put($bootstrapPath, implode("\n", $bootstrapLines) . "\n");

// Drop the orphaned `_img/.config.php` from 1.0.4-beta dev (between commit
// 6d0e40f and this fixup). Harmless if missing.
$staleConfigPath = rex_path::addonAssets(Config::ADDON, '_img/.config.php');
if (is_file($staleConfigPath)) {
    rex_file::delete($staleConfigPath);
}

// Article/template caches generated before this addon was active still contain
// `REX_PIC[...]` / `REX_VIDEO[...]` as literal text — at parse time the var
// wasn't registered, so `rex_var::parse` left them untouched. REDAXO doesn't
// auto-clear caches on install/activate, so flush them here to force a clean
// regen on next render. Also runs on update/reinstall, which is what we want
// when `getOutput()` semantics change between releases.
rex_delete_cache();
