package: massif_media
version: 1.0.0
author: Yves Torres
supportpage: massif.ch

requires:
  redaxo: '^5.13.0'
  php:
    version: '>=8.2'

installer_ignore:
  - .DS_Store
  - .git
  - .gitignore
  - .vscode
  - .idea
  - node_modules
  - _legacy_reference

page:
  title: 'MASSIF Media'
  perm: massif_media[]
  icon: rex-icon fa-image
  subpages:
    settings:
      title: 'Einstellungen'
      icon: rex-icon fa-cog
      subpages:
        general: { title: 'Allgemein' }
        placeholder: { title: 'Placeholder' }
        cdn: { title: 'CDN' }
        security: { title: 'Sicherheit & Cache' }
    docs:
      title: 'Dokumentation'
      icon: rex-icon fa-book
      subPath: README.md
